//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvgFlight
    {
        public int FromAirport { get; set; }
        public int ToAirport { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> FlightH { get; set; }
        public Nullable<decimal> FlightM { get; set; }
    }
}
