//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxCrew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxCrew()
        {
            this.EmployeeCalendars = new HashSet<EmployeeCalendar>();
            this.EmployeeCalendarSpliteds = new HashSet<EmployeeCalendarSplited>();
        }
    
        public int Id { get; set; }
        public int BoxId { get; set; }
        public int JobGroupId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> AvailabilityId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReportingTime { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCalendar> EmployeeCalendars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCalendarSplited> EmployeeCalendarSpliteds { get; set; }
    }
}
