//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxFlightPlanItem
    {
        public int Id { get; set; }
        public int BoxId { get; set; }
        public int ItemId { get; set; }
        public int CalanderId { get; set; }
        public Nullable<bool> SplitDuty { get; set; }
        public Nullable<int> SplitDutyPairId { get; set; }
    
        public virtual Box Box { get; set; }
    }
}
