//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaoBasicLicenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaoBasicLicenseType()
        {
            this.CaoBasics = new HashSet<CaoBasic>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ResultTextCatA { get; set; }
        public string ResultTextCatB { get; set; }
        public string ResultTextCatC { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaoBasic> CaoBasics { get; set; }
    }
}
