//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Document1 = new HashSet<Document>();
            this.PersonEducationDocuments = new HashSet<PersonEducationDocument>();
            this.PersonRatingDocuments = new HashSet<PersonRatingDocument>();
            this.BookFiles = new HashSet<BookFile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public string FileUrl { get; set; }
        public string Title { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string SysUrl { get; set; }
        public string FileType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document1 { get; set; }
        public virtual Document Document2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonEducationDocument> PersonEducationDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRatingDocument> PersonRatingDocuments { get; set; }
        public virtual PersonDocument PersonDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFile> BookFiles { get; set; }
    }
}
