//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCalendarSplited
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateContact { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<System.DateTime> DateCease { get; set; }
        public Nullable<bool> IsHomeBase { get; set; }
        public int EmployeeId { get; set; }
        public bool IsDismissed { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual BoxCrew BoxCrew { get; set; }
        public virtual EmployeeCalendar EmployeeCalendar { get; set; }
    }
}
