//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPlanStatu
    {
        public int Id { get; set; }
        public int FlighPlanId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public System.DateTime DateApproved { get; set; }
        public int ApproveTypeId { get; set; }
        public string Remark { get; set; }
    
        public virtual FlightPlan FlightPlan { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
