//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPlanItemPermit
    {
        public int Id { get; set; }
        public int FlightPlanId { get; set; }
        public int PermitId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateFlight { get; set; }
        public Nullable<int> CalanderId { get; set; }
    
        public virtual FlightPermit FlightPermit { get; set; }
        public virtual FlightPlanItem FlightPlanItem { get; set; }
    }
}
