//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightCrewChangeHistory
    {
        public int Id { get; set; }
        public int FlightCrewId { get; set; }
        public int ReasonId { get; set; }
        public System.DateTime DateChange { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NewEmployeeId { get; set; }
        public Nullable<int> NewGroupId { get; set; }
        public string Remark { get; set; }
    }
}
