//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightStatusWeather
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<decimal> Temprature { get; set; }
        public Nullable<decimal> WindSpeed { get; set; }
        public Nullable<decimal> WindBearing { get; set; }
        public Nullable<decimal> CloudCover { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> DewPoint { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> Visibility { get; set; }
        public string Details { get; set; }
        public string Icon { get; set; }
    
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
