//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightStatusLog
    {
        public int ID { get; set; }
        public int FlightID { get; set; }
        public int FlightStatusID { get; set; }
        public System.DateTime Date { get; set; }
        public string Remark { get; set; }
        public int UserId { get; set; }
    
        public virtual FlightStatu FlightStatu { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
