//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightInformation()
        {
            this.FlightCrews = new HashSet<FlightCrew>();
            this.FlightDelays = new HashSet<FlightDelay>();
            this.FlightStatusLogs = new HashSet<FlightStatusLog>();
            this.FlightLinks = new HashSet<FlightLink>();
            this.FlightLinks1 = new HashSet<FlightLink>();
            this.FlightStatusWeathers = new HashSet<FlightStatusWeather>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> AirlineOperatorsID { get; set; }
        public Nullable<int> FlightGroupID { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<byte> FlightM { get; set; }
        public Nullable<int> BlockH { get; set; }
        public Nullable<byte> BlockM { get; set; }
        public Nullable<decimal> GWTO { get; set; }
        public Nullable<decimal> GWLand { get; set; }
        public Nullable<decimal> FuelPlanned { get; set; }
        public Nullable<decimal> FuelActual { get; set; }
        public Nullable<decimal> FuelDeparture { get; set; }
        public Nullable<decimal> FuelArrival { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxChild { get; set; }
        public Nullable<int> CargoWeight { get; set; }
        public Nullable<int> CargoUnitID { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public Nullable<int> BaggageWeight { get; set; }
        public Nullable<int> FuelUnitID { get; set; }
        public string ArrivalRemark { get; set; }
        public string DepartureRemark { get; set; }
        public Nullable<int> EstimatedDelay { get; set; }
        public Nullable<int> FlightStatusUserId { get; set; }
        public Nullable<int> CancelReasonId { get; set; }
        public string CancelRemark { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> OToAirportId { get; set; }
        public Nullable<System.DateTime> OSTA { get; set; }
        public string OToAirportIATA { get; set; }
        public Nullable<int> RedirectReasonId { get; set; }
        public string RedirectRemark { get; set; }
        public Nullable<System.DateTime> RedirectDate { get; set; }
        public Nullable<bool> IsApplied { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<int> FlightPlanRegisterId { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> RampReasonId { get; set; }
        public string RampRemark { get; set; }
        public Nullable<System.DateTime> RampDate { get; set; }
        public Nullable<int> FPFlightHH { get; set; }
        public Nullable<int> FPFlightMM { get; set; }
        public Nullable<decimal> FPFuel { get; set; }
        public Nullable<decimal> Defuel { get; set; }
        public Nullable<bool> SplitDuty { get; set; }
    
        public virtual Ac_MSN Ac_MSN { get; set; }
        public virtual AircraftType AircraftType { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual Box Box { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightCrew> FlightCrews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightDelay> FlightDelays { get; set; }
        public virtual FlightGroup FlightGroup { get; set; }
        public virtual FlightStatu FlightStatu { get; set; }
        public virtual FlightPlanItem FlightPlanItem { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightStatusLog> FlightStatusLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightLink> FlightLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightLink> FlightLinks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightStatusWeather> FlightStatusWeathers { get; set; }
    }
}
