//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightCrew
    {
        public int Id { get; set; }
        public int FlightInformationId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> FlightPlanCrewId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FlightPlanCalanderCrew FlightPlanCalanderCrew { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
