//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightPlanCalanderCrew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightPlanCalanderCrew()
        {
            this.FlightCrews = new HashSet<FlightCrew>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public Nullable<int> CalanderId { get; set; }
        public int GroupId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightPlanItemId { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> AvailabilityId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FlighPlanCalendar FlighPlanCalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightCrew> FlightCrews { get; set; }
        public virtual FlightPlanItem FlightPlanItem { get; set; }
        public virtual Box Box { get; set; }
    }
}
