//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_DelayCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_DelayCode()
        {
            this.G_DelayCode1 = new HashSet<G_DelayCode>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Title { get; set; }
        public string DelayCode { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_DelayCode> G_DelayCode1 { get; set; }
        public virtual G_DelayCode G_DelayCode2 { get; set; }
    }
}
