//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_OpOneDelayType
    {
        public System.Guid PKG_OpOneDelayType { get; set; }
        public string Title { get; set; }
        public string DelayCodeStartWith { get; set; }
        public string Description { get; set; }
    }
}
