//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelperPerson
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateExpireNDT { get; set; }
        public Nullable<int> RemainNDT { get; set; }
        public Nullable<int> RemainMedical { get; set; }
        public Nullable<int> RemainCAO { get; set; }
        public Nullable<int> RemainPassport { get; set; }
        public Nullable<int> RemainLicence { get; set; }
        public Nullable<int> RemainSimulator { get; set; }
        public Nullable<int> RemainLanguageCourse { get; set; }
        public Nullable<int> RemainProficiency { get; set; }
        public Nullable<int> RemainCMC { get; set; }
        public Nullable<int> RemainSEPT { get; set; }
        public Nullable<int> RemainLPR { get; set; }
        public Nullable<int> RemainDG { get; set; }
        public Nullable<int> RemainCRM { get; set; }
        public Nullable<int> RemainCCRM { get; set; }
        public Nullable<int> RemainSMS { get; set; }
        public Nullable<int> RemainAvSec { get; set; }
        public Nullable<int> RemainUpsetRecoveryTraining { get; set; }
        public Nullable<int> RemainColdWeather { get; set; }
        public Nullable<int> RemainHotWeather { get; set; }
        public Nullable<int> RemainSEPTP { get; set; }
        public Nullable<int> RemainFirstAid { get; set; }
        public Nullable<int> RemainLicenceIR { get; set; }
    }
}
