//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateSent { get; set; }
        public Nullable<int> SenderId { get; set; }
        public bool SMS { get; set; }
        public bool Email { get; set; }
        public bool App { get; set; }
        public Nullable<System.DateTime> DateSMSSent { get; set; }
        public Nullable<System.DateTime> DateEmailSent { get; set; }
        public Nullable<System.DateTime> DateAppSent { get; set; }
        public string SMSIssue { get; set; }
        public string EmailIssue { get; set; }
        public string AppIssue { get; set; }
        public Nullable<System.DateTime> DateAppVisited { get; set; }
        public int TypeId { get; set; }
        public string Subject { get; set; }
        public Nullable<int> ModuleId { get; set; }
    }
}
