//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEducationDocument
    {
        public int PersonEducationId { get; set; }
        public int DocumentId { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual PersonEducation PersonEducation { get; set; }
    }
}
