//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCustomer
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<decimal> DateJoinCompanyP { get; set; }
        public bool IsActive { get; set; }
        public decimal DateRegisterP { get; set; }
        public Nullable<decimal> DateConfirmedP { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateActiveStart { get; set; }
        public Nullable<System.DateTime> DateActiveEnd { get; set; }
        public Nullable<decimal> DateLastLoginP { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual JobGroup JobGroup { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Person Person { get; set; }
    }
}
