//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonCaoLicenses = new HashSet<PersonCaoLicense>();
            this.PersonCaoLicenceHistories = new HashSet<PersonCaoLicenceHistory>();
            this.PersonDocuments = new HashSet<PersonDocument>();
            this.PersonCustomers = new HashSet<PersonCustomer>();
            this.PersonEducations = new HashSet<PersonEducation>();
            this.PersonExperienses = new HashSet<PersonExperiense>();
            this.PersonRatings = new HashSet<PersonRating>();
            this.PersonAircraftTypes = new HashSet<PersonAircraftType>();
            this.PersonCourses = new HashSet<PersonCourse>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string EmailPassword { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<int> CaoIntervalCalanderTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public string Remark { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public Nullable<System.DateTime> DateIssueNDT { get; set; }
        public Nullable<int> IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public Nullable<int> NDTIntervalCalanderTypeId { get; set; }
        public Nullable<bool> IsAuditor { get; set; }
        public Nullable<bool> IsAuditee { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> CityId { get; set; }
        public string FatherName { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public string UserId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CustomerCreatorId { get; set; }
        public Nullable<System.DateTime> DateExpireNDT { get; set; }
        public Nullable<System.DateTime> ProficiencyExpireDate { get; set; }
        public Nullable<System.DateTime> CrewMemberCertificateExpireDate { get; set; }
        public Nullable<System.DateTime> LicenceExpireDate { get; set; }
        public Nullable<System.DateTime> SimulatorLastCheck { get; set; }
        public Nullable<System.DateTime> SimulatorNextCheck { get; set; }
        public string RampPassNo { get; set; }
        public Nullable<System.DateTime> RampPassExpireDate { get; set; }
        public Nullable<System.DateTime> LanguageCourseExpireDate { get; set; }
        public string LicenceTitle { get; set; }
        public Nullable<System.DateTime> LicenceInitialIssue { get; set; }
        public string RaitingCertificates { get; set; }
        public Nullable<System.DateTime> LicenceIssueDate { get; set; }
        public string LicenceDescription { get; set; }
        public Nullable<int> ProficiencyCheckType { get; set; }
        public Nullable<System.DateTime> ProficiencyCheckDate { get; set; }
        public Nullable<System.DateTime> ProficiencyValidUntil { get; set; }
        public Nullable<int> ICAOLPRLevel { get; set; }
        public Nullable<System.DateTime> ICAOLPRValidUntil { get; set; }
        public Nullable<int> MedicalClass { get; set; }
        public string CMCEmployedBy { get; set; }
        public string CMCOccupation { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> ProficiencyIPC { get; set; }
        public Nullable<bool> ProficiencyOPC { get; set; }
        public string MedicalLimitation { get; set; }
        public string ProficiencyDescription { get; set; }
        public Nullable<System.DateTime> VisaExpireDate { get; set; }
        public Nullable<System.DateTime> SEPTIssueDate { get; set; }
        public Nullable<System.DateTime> SEPTExpireDate { get; set; }
        public Nullable<System.DateTime> DangerousGoodsIssueDate { get; set; }
        public Nullable<System.DateTime> DangerousGoodsExpireDate { get; set; }
        public Nullable<System.DateTime> CCRMIssueDate { get; set; }
        public Nullable<System.DateTime> CCRMExpireDate { get; set; }
        public Nullable<System.DateTime> CRMIssueDate { get; set; }
        public Nullable<System.DateTime> CRMExpireDate { get; set; }
        public Nullable<System.DateTime> SMSIssueDate { get; set; }
        public Nullable<System.DateTime> SMSExpireDate { get; set; }
        public Nullable<System.DateTime> AviationSecurityIssueDate { get; set; }
        public Nullable<System.DateTime> AviationSecurityExpireDate { get; set; }
        public Nullable<System.DateTime> EGPWSIssueDate { get; set; }
        public Nullable<System.DateTime> EGPWSExpireDate { get; set; }
        public Nullable<System.DateTime> UpsetRecoveryTrainingIssueDate { get; set; }
        public Nullable<System.DateTime> UpsetRecoveryTrainingExpireDate { get; set; }
        public Nullable<System.DateTime> ColdWeatherOperationIssueDate { get; set; }
        public Nullable<System.DateTime> HotWeatherOperationIssueDate { get; set; }
        public Nullable<System.DateTime> PBNRNAVIssueDate { get; set; }
        public Nullable<System.DateTime> PBNRNAVExpireDate { get; set; }
        public Nullable<System.DateTime> ColdWeatherOperationExpireDate { get; set; }
        public Nullable<System.DateTime> HotWeatherOperationExpireDate { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> SEPTPIssueDate { get; set; }
        public Nullable<System.DateTime> SEPTPExpireDate { get; set; }
        public Nullable<System.DateTime> FirstAidIssueDate { get; set; }
        public Nullable<System.DateTime> FirstAidExpireDate { get; set; }
        public Nullable<System.DateTime> LicenceIRExpireDate { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Option Option1 { get; set; }
        public virtual Option Option2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCaoLicense> PersonCaoLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCaoLicenceHistory> PersonCaoLicenceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonDocument> PersonDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCustomer> PersonCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonExperiense> PersonExperienses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRating> PersonRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAircraftType> PersonAircraftTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCourse> PersonCourses { get; set; }
    }
}
