//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCourse
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<bool> Quarantine { get; set; }
        public string Grade { get; set; }
        public string CerNumber { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<decimal> DateIssueP { get; set; }
        public Nullable<decimal> DateExpireP { get; set; }
        public string CerUrl { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<bool> StatusConfirmed { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
