//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCaoLicense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonCaoLicense()
        {
            this.PersonCaoLicenceHistories = new HashSet<PersonCaoLicenceHistory>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> CaoBasicTypeId { get; set; }
        public Nullable<int> CaoCategoryId { get; set; }
        public Nullable<int> CaoBasicId { get; set; }
        public Nullable<System.DateTime> DateLicense { get; set; }
        public string Remark { get; set; }
        public string Result { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> Quarantine { get; set; }
    
        public virtual CaoBasic CaoBasic { get; set; }
        public virtual CaoBasicType CaoBasicType { get; set; }
        public virtual CaoCategory CaoCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCaoLicenceHistory> PersonCaoLicenceHistories { get; set; }
        public virtual Person Person { get; set; }
    }
}
