//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCaoLicenceHistory
    {
        public int Id { get; set; }
        public int CaoUserLicenseId { get; set; }
        public int PersonId { get; set; }
        public int CaoBasicTypeId { get; set; }
        public int CaoCategoryId { get; set; }
        public System.DateTime DateLicense { get; set; }
        public string Remark { get; set; }
    
        public virtual CaoBasicType CaoBasicType { get; set; }
        public virtual CaoCategory CaoCategory { get; set; }
        public virtual PersonCaoLicense PersonCaoLicense { get; set; }
        public virtual Person Person { get; set; }
    }
}
