//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAircraftType
    {
        public int Id { get; set; }
        public int AircraftTypeId { get; set; }
        public int PersonId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateLimitBegin { get; set; }
        public Nullable<System.DateTime> DateLimitEnd { get; set; }
        public string Remark { get; set; }
    
        public virtual AircraftType AircraftType { get; set; }
        public virtual Person Person { get; set; }
    }
}
