//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumActiveCourse
    {
        public int CustomerId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Assigned { get; set; }
        public Nullable<int> Registered { get; set; }
        public Nullable<int> Unregistered { get; set; }
        public Nullable<int> ActiveLearner { get; set; }
        public Nullable<int> Canceled { get; set; }
        public Nullable<int> DoneLearner { get; set; }
        public Nullable<int> Passed { get; set; }
        public Nullable<int> Failed { get; set; }
    }
}
