//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumEmployeeExp
    {
        public int Id { get; set; }
        public Nullable<int> ExpCompanyUnknown { get; set; }
        public Nullable<int> ExpCompany0005 { get; set; }
        public Nullable<int> ExpCompany0510 { get; set; }
        public Nullable<int> ExpCompany1020 { get; set; }
        public Nullable<int> ExpCompany2000 { get; set; }
        public Nullable<int> ExpUnknown { get; set; }
        public Nullable<int> Exp0005 { get; set; }
        public Nullable<int> Exp0510 { get; set; }
        public Nullable<int> Exp1020 { get; set; }
        public Nullable<int> Exp2000 { get; set; }
    }
}
