//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBox
    {
        public int Id { get; set; }
        public int FlightPlanId { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> DefaultStart { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> DefaultEnd { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CalanderId { get; set; }
        public string Flights { get; set; }
        public Nullable<int> Duty { get; set; }
        public Nullable<int> Flight { get; set; }
        public Nullable<int> NotAllAssignedCount { get; set; }
        public Nullable<int> CrewProblemCount { get; set; }
        public Nullable<int> AssignedCrewCount { get; set; }
        public Nullable<System.DateTime> RestUntil { get; set; }
        public Nullable<System.DateTime> RestFrom { get; set; }
        public int MaxFDP { get; set; }
        public Nullable<double> MaxFDPExtended { get; set; }
        public int IsDutyOver { get; set; }
        public Nullable<int> WOCL { get; set; }
        public int WOCLError { get; set; }
        public Nullable<int> Sector { get; set; }
    }
}
