//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCrewTimeDetail
    {
        public string PID { get; set; }
        public int PersonId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<int> ExpCompany { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string ImageUrl { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string PPLNumber { get; set; }
        public Nullable<System.DateTime> PPLDateIssue { get; set; }
        public Nullable<System.DateTime> PPLDateExpire { get; set; }
        public Nullable<int> PPLExpireStatus { get; set; }
        public string CPLNumber { get; set; }
        public Nullable<System.DateTime> CPLDateIssue { get; set; }
        public Nullable<System.DateTime> CPLDateExpire { get; set; }
        public Nullable<int> CPLExpireStatus { get; set; }
        public string ATPLNumber { get; set; }
        public Nullable<System.DateTime> ATPLDateIssue { get; set; }
        public Nullable<System.DateTime> ATPLDateExpire { get; set; }
        public Nullable<int> ATPLExpireStatus { get; set; }
        public string MCCNumber { get; set; }
        public Nullable<System.DateTime> MCCDateIssue { get; set; }
        public Nullable<int> MCCExpireStatus { get; set; }
        public Nullable<System.DateTime> MCCDateExpire { get; set; }
        public Nullable<int> CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIATA { get; set; }
        public System.DateTime CDate { get; set; }
        public string DateStr { get; set; }
        public Nullable<double> Day1_Duty { get; set; }
        public Nullable<int> Day1_Flight { get; set; }
        public Nullable<double> Day7_Duty { get; set; }
        public Nullable<int> Day7_Flight { get; set; }
        public Nullable<double> Day14_Duty { get; set; }
        public Nullable<int> Day14_Flight { get; set; }
        public Nullable<double> Day28_Duty { get; set; }
        public Nullable<int> Day28_Flight { get; set; }
        public Nullable<double> Year_Duty { get; set; }
        public Nullable<int> Year_Flight { get; set; }
        public Nullable<int> CalendarStatusId { get; set; }
        public string CalendarStatus { get; set; }
        public int IsMedicalExpired { get; set; }
        public int IsAvSecExpired { get; set; }
        public int IsCCRMExpired { get; set; }
        public int IsCMCExpired { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int IsCRMExpired { get; set; }
        public int IsDGExpired { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public int IsLicenceExpired { get; set; }
        public int IsLicenceIRExpired { get; set; }
        public int IsLPRExpired { get; set; }
        public int IsFirstAidExpired { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int IsSEPTExpired { get; set; }
        public int IsSEPTPExpired { get; set; }
        public int IsSMSExpired { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
    }
}
