//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNotification
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime DateSent { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string Sender { get; set; }
        public bool SMS { get; set; }
        public bool Email { get; set; }
        public bool App { get; set; }
        public Nullable<System.DateTime> DateSMSSent { get; set; }
        public int IsSMSSent { get; set; }
        public Nullable<System.DateTime> DateEmailSent { get; set; }
        public int IsEmailSent { get; set; }
        public Nullable<System.DateTime> DateAppSent { get; set; }
        public int IsAppSent { get; set; }
        public string SMSIssue { get; set; }
        public string EmailIssue { get; set; }
        public string AppIssue { get; set; }
        public Nullable<System.DateTime> DateAppVisited { get; set; }
        public int TypeId { get; set; }
        public string PID { get; set; }
        public string NID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string UserEmail { get; set; }
        public string IDNo { get; set; }
        public int PersonId { get; set; }
        public string Type { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string Subject { get; set; }
        public string Abstract { get; set; }
    }
}
