//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCrew
    {
        public int Id { get; set; }
        public int FlightInformationId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightPlanCrewId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CalanderId { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string PID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> ActualFlightHOffBlock { get; set; }
        public Nullable<decimal> ActualFlightMOffBlock { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<int> ActualFlightHTakeoff { get; set; }
        public Nullable<decimal> ActualFlightMTakeoff { get; set; }
        public Nullable<int> TotalFlightMinutesOffBlock { get; set; }
        public Nullable<decimal> TotalFlightHoursOffBlock { get; set; }
        public Nullable<decimal> PastHoursFromOffBlock { get; set; }
        public Nullable<System.DateTime> ActualDateOffBlock { get; set; }
    }
}
