//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeAge
    {
        public Nullable<int> CustomerId { get; set; }
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public int AgeUnknown { get; set; }
        public int Age0025 { get; set; }
        public int Age2530 { get; set; }
        public int Age3040 { get; set; }
        public int Age4050 { get; set; }
        public int Age5000 { get; set; }
    }
}
