//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightDelay
    {
        public int ID { get; set; }
        public int FlightId { get; set; }
        public int DelayCodeId { get; set; }
        public Nullable<int> DelayHH { get; set; }
        public Nullable<int> DelayMM { get; set; }
        public string Remark { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public int DelayCategoryId { get; set; }
        public string DelayRemark { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<byte> FlightM { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string FlightType { get; set; }
        public string FlightTypeAbr { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FromAirportName { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<int> FromAirportCityId { get; set; }
        public string ToAirportName { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> ToAirportCityId { get; set; }
        public string FromAirportCity { get; set; }
        public string ToAirportCity { get; set; }
        public string AircraftType { get; set; }
        public string Register { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<int> DelayOffBlock { get; set; }
        public Nullable<int> DelayTakeoff { get; set; }
        public Nullable<int> DelayOnBlock { get; set; }
        public Nullable<int> DelayLanding { get; set; }
        public int ActualFlightHOffBlock { get; set; }
        public decimal ActualFlightMOffBlock { get; set; }
        public int ActualFlightHTakeoff { get; set; }
        public decimal ActualFlightMTakeoff { get; set; }
        public Nullable<int> BaseId { get; set; }
        public string BaseIATA { get; set; }
        public string BaseName { get; set; }
        public string Route { get; set; }
    }
}
