//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightPlanRegisterAssigned
    {
        public int id { get; set; }
        public Nullable<int> DesignedRegisterCount { get; set; }
        public Nullable<int> CompletedAssignedRegisterCount { get; set; }
        public Nullable<int> NotCompletedAssignedRegisterCount { get; set; }
    }
}
