//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightPlanCalanderCrew
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CalanderId { get; set; }
        public Nullable<int> FlightPlanId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> AvStatusId { get; set; }
        public string AvStatus { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string Remark { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> FlightPlanItemId { get; set; }
        public string PID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<int> ExpCompany { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string PPLNumber { get; set; }
        public Nullable<System.DateTime> PPLDateIssue { get; set; }
        public Nullable<System.DateTime> PPLDateExpire { get; set; }
        public Nullable<int> PPLExpireStatus { get; set; }
        public string CPLNumber { get; set; }
        public Nullable<System.DateTime> CPLDateIssue { get; set; }
        public Nullable<System.DateTime> CPLDateExpire { get; set; }
        public Nullable<int> CPLExpireStatus { get; set; }
        public string ATPLNumber { get; set; }
        public Nullable<System.DateTime> ATPLDateIssue { get; set; }
        public Nullable<System.DateTime> ATPLDateExpire { get; set; }
        public Nullable<int> ATPLExpireStatus { get; set; }
        public string MCCNumber { get; set; }
        public Nullable<System.DateTime> MCCDateIssue { get; set; }
        public Nullable<System.DateTime> MCCDateExpire { get; set; }
        public Nullable<int> MCCExpireStatus { get; set; }
        public Nullable<int> CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIATA { get; set; }
        public int IsMedicalExpired { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public string Flights { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
    }
}
