//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightDelayCode
    {
        public int FlightId { get; set; }
        public Nullable<int> FlighrDelayId { get; set; }
        public Nullable<int> HH { get; set; }
        public Nullable<int> MM { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public int DelayCategoryId { get; set; }
        public Nullable<int> AirlineId { get; set; }
        public int DelayCodeId { get; set; }
        public int Selected { get; set; }
        public string Remark { get; set; }
    }
}
