//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersonCaoLicense
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> CaoBasicTypeId { get; set; }
        public Nullable<int> CaoCategoryId { get; set; }
        public Nullable<int> CaoBasicId { get; set; }
        public Nullable<System.DateTime> DateLicense { get; set; }
        public string Remark { get; set; }
        public string Result { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> Quarantine { get; set; }
    }
}
