//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPost
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> People { get; set; }
    }
}
