//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightPlanCalendarRegister
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int PlannedRegisterId { get; set; }
        public int RegisterId { get; set; }
        public int FlightPlanId { get; set; }
    }
}
