//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBookApplicableEmployee
    {
        public int EmployeeId { get; set; }
        public int BookId { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> EmployeeCustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<int> CaoIntervalCalanderTypeId { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public Nullable<System.DateTime> DateIssueNDT { get; set; }
        public Nullable<int> IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public Nullable<int> NDTIntervalCalanderTypeId { get; set; }
        public string IDNo { get; set; }
        public string EmployeeImageUrl { get; set; }
        public Nullable<int> CustomerCreatorId { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NDTIntervalCalanderType { get; set; }
        public string Customer { get; set; }
        public int PersonId { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> DateRelease { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string ISSNPrint { get; set; }
        public string ISSNElectronic { get; set; }
        public string DOI { get; set; }
        public string Pages { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Category { get; set; }
        public string Publisher { get; set; }
        public string PublisherWebsite { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Abstract { get; set; }
        public string ImageUrl { get; set; }
        public string Keywords { get; set; }
        public string AuthorIds { get; set; }
        public string Authors { get; set; }
        public string TranslatorIds { get; set; }
        public Nullable<System.DateTime> DateExposure { get; set; }
        public int IsExposed { get; set; }
        public bool IsVisited { get; set; }
        public bool IsDownloaded { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public Nullable<System.DateTime> DateDownload { get; set; }
        public string No { get; set; }
        public string Sender { get; set; }
        public string DateConference { get; set; }
        public Nullable<int> ConferenceLocationId { get; set; }
        public string Conference { get; set; }
        public Nullable<int> JournalId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> NumberOfLessens { get; set; }
        public string ExternalUrl { get; set; }
        public string Duration { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> DateDeadline { get; set; }
        public string Language { get; set; }
        public string Type { get; set; }
        public string Journal { get; set; }
        public string PublishedIn { get; set; }
        public string INSPECAccessionNumber { get; set; }
        public string DateEffective { get; set; }
        public string Edition { get; set; }
    }
}
