//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeLight
    {
        public int Id { get; set; }
        public string PID { get; set; }
        public Nullable<int> CurrentLocationAirport { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<int> ExpCompany { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<int> CaoIntervalCalanderTypeId { get; set; }
        public string Remark { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public Nullable<System.DateTime> DateIssueNDT { get; set; }
        public Nullable<int> IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public Nullable<int> NDTIntervalCalanderTypeId { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> CityId { get; set; }
        public string FatherName { get; set; }
        public string IDNo { get; set; }
        public string UserId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CustomerCreatorId { get; set; }
        public Nullable<int> Age { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> OrgRoleId { get; set; }
        public string LocationPhone { get; set; }
        public bool IsMainLocation { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NDTIntervalCalanderType { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Country { get; set; }
        public string CityFullName { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public Nullable<int> RootLocation { get; set; }
        public string LocationCode { get; set; }
        public int PersonId { get; set; }
        public int EmployeeLocationId { get; set; }
        public string Post { get; set; }
        public Nullable<int> RemainNDT { get; set; }
        public Nullable<int> RemainCAO { get; set; }
        public Nullable<int> RemainMedical { get; set; }
        public Nullable<int> RemainPassport { get; set; }
        public int IsNDTExpired { get; set; }
        public int IsNDTExpiring { get; set; }
        public int IsCAOExpired { get; set; }
        public int IsCAOExpiring { get; set; }
        public int IsMedicalExpired { get; set; }
        public int IsMedicalExpiring { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsPassportExpiring { get; set; }
    }
}
