//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeExp
    {
        public Nullable<int> CustomerId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<int> ExpCompany { get; set; }
        public int ExpCompanyUnknown { get; set; }
        public int ExpCompany0005 { get; set; }
        public int ExpCompany0510 { get; set; }
        public int ExpCompany1020 { get; set; }
        public int ExpCompany2000 { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public int ExpUnknown { get; set; }
        public int Exp0005 { get; set; }
        public int Exp0510 { get; set; }
        public int Exp1020 { get; set; }
        public int Exp2000 { get; set; }
    }
}
