//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBook
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> DateRelease { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string ISSNPrint { get; set; }
        public string ISSNElectronic { get; set; }
        public string DOI { get; set; }
        public string Pages { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Category { get; set; }
        public string Publisher { get; set; }
        public string PublisherWebsite { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Abstract { get; set; }
        public string ImageUrl { get; set; }
        public string Keywords { get; set; }
        public string AuthorIds { get; set; }
        public string Authors { get; set; }
        public string TranslatorIds { get; set; }
        public Nullable<System.DateTime> DateExposure { get; set; }
        public int IsExposed { get; set; }
        public string No { get; set; }
        public string Sender { get; set; }
        public string DateConference { get; set; }
        public Nullable<int> ConferenceLocationId { get; set; }
        public string Conference { get; set; }
        public Nullable<int> JournalId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> NumberOfLessens { get; set; }
        public string ExternalUrl { get; set; }
        public string Duration { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> DateDeadline { get; set; }
        public string Language { get; set; }
        public string Type { get; set; }
        public string Journal { get; set; }
        public string PublishedIn { get; set; }
        public string INSPECAccessionNumber { get; set; }
        public string DateEffective { get; set; }
        public string Edition { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Visited { get; set; }
        public Nullable<int> NotVisited { get; set; }
        public Nullable<int> Downloaded { get; set; }
        public Nullable<int> NotDownloaded { get; set; }
    }
}
