//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCrew2
    {
        public int FlightId { get; set; }
        public Nullable<byte> BlockM { get; set; }
        public Nullable<int> BlockH { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<byte> FlightM { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string FlightType { get; set; }
        public string FlightTypeAbr { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<System.DateTime> STAPlanned { get; set; }
        public Nullable<System.DateTime> STDPlanned { get; set; }
        public Nullable<int> FlightHPlanned { get; set; }
        public Nullable<int> FlightMPlanned { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string FromAirportName { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<int> FromAirportCityId { get; set; }
        public string ToAirportIATA { get; set; }
        public string ToAirportName { get; set; }
        public Nullable<int> ToAirportCityId { get; set; }
        public string FromAirportCity { get; set; }
        public string ToAirportCity { get; set; }
        public string AircraftType { get; set; }
        public string Register { get; set; }
        public Nullable<int> MSN { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<int> DelayOffBlock { get; set; }
        public Nullable<int> DelayOnBlock { get; set; }
        public Nullable<int> DelayTakeoff { get; set; }
        public Nullable<int> DelayLanding { get; set; }
        public Nullable<int> IsDelayOffBlock { get; set; }
        public Nullable<int> IsDelayTakeoff { get; set; }
        public Nullable<int> IsDelayOnBlock { get; set; }
        public Nullable<int> IsDelayLanding { get; set; }
        public Nullable<int> ActualFlightHOffBlock { get; set; }
        public Nullable<int> ActualFlightHTakeoff { get; set; }
        public Nullable<decimal> ActualFlightMOffBlock { get; set; }
        public Nullable<decimal> ActualFlightMTakeoff { get; set; }
        public Nullable<int> CancelReasonId { get; set; }
        public string CancelRemark { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> CalendarId { get; set; }
        public int Id { get; set; }
        public int PositionId { get; set; }
        public int EmployeeId { get; set; }
        public string Position { get; set; }
        public string PID { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string ImageUrl { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroup { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public int IsMedicalExpired { get; set; }
        public string PPLNumber { get; set; }
        public Nullable<System.DateTime> PPLDateIssue { get; set; }
        public Nullable<System.DateTime> PPLDateExpire { get; set; }
        public Nullable<int> PPLExpireStatus { get; set; }
        public string CPLNumber { get; set; }
        public Nullable<System.DateTime> CPLDateIssue { get; set; }
        public Nullable<System.DateTime> CPLDateExpire { get; set; }
        public Nullable<int> CPLExpireStatus { get; set; }
        public string ATPLNumber { get; set; }
        public Nullable<System.DateTime> ATPLDateIssue { get; set; }
        public Nullable<System.DateTime> ATPLDateExpire { get; set; }
        public Nullable<int> ATPLExpireStatus { get; set; }
        public string MCCNumber { get; set; }
        public Nullable<System.DateTime> MCCDateIssue { get; set; }
        public Nullable<System.DateTime> MCCDateExpire { get; set; }
        public Nullable<int> MCCExpireStatus { get; set; }
        public Nullable<int> CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIATA { get; set; }
        public Nullable<System.DateTime> ReportingTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> Ground { get; set; }
        public Nullable<int> BoxBegin { get; set; }
        public Nullable<int> Duty { get; set; }
    }
}
