//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeLocation
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int LocationId { get; set; }
        public bool IsMainLocation { get; set; }
        public Nullable<int> OrgRoleId { get; set; }
        public Nullable<decimal> DateActiveStartP { get; set; }
        public Nullable<decimal> DateActiveEndP { get; set; }
        public Nullable<System.DateTime> DateActiveStart { get; set; }
        public Nullable<System.DateTime> DateActiveEnd { get; set; }
        public string Remark { get; set; }
        public string Phone { get; set; }
        public string OrgRole { get; set; }
        public string Title { get; set; }
        public string FullCode { get; set; }
        public int CustomerId { get; set; }
        public string Root2Code { get; set; }
        public string Root2Title { get; set; }
    }
}
