//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCertificate
    {
        public string CourseNo { get; set; }
        public System.DateTime CourseDateStart { get; set; }
        public string CourseInstructor { get; set; }
        public string CourseTitle { get; set; }
        public string CourseTrainingDirector { get; set; }
        public Nullable<bool> CourseRecurrent { get; set; }
        public Nullable<int> CourseInterval { get; set; }
        public Nullable<int> CourseCalanderTypeId { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseLocation { get; set; }
        public string CourseDepartment { get; set; }
        public Nullable<int> CourseOrganizationId { get; set; }
        public Nullable<int> CourseDurationUnitId { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public string CourseRemark { get; set; }
        public string CourseTypeTitle { get; set; }
        public string CourseCategoryTitle { get; set; }
        public string CaoTypeTitle { get; set; }
        public Nullable<int> CaoTypeId { get; set; }
        public string CourseOrganization { get; set; }
        public string CourseDurationUnit { get; set; }
        public string CourseDuration2 { get; set; }
        public string CourseCalendarType { get; set; }
        public Nullable<int> CourseCustomerId { get; set; }
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CerNumber { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string CerUrl { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<bool> StatusConfirmed { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<int> CaoIntervalCalanderTypeId { get; set; }
        public string StampUrl { get; set; }
        public string StampNumber { get; set; }
        public string TechLogNo { get; set; }
        public Nullable<System.DateTime> DateIssueNDT { get; set; }
        public Nullable<int> IntervalNDT { get; set; }
        public string NDTNumber { get; set; }
        public Nullable<int> NDTIntervalCalanderTypeId { get; set; }
        public string IDNo { get; set; }
        public Nullable<int> CustomerCreatorId { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NDTIntervalCalanderType { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> ExpireStatus { get; set; }
        public Nullable<long> RankLast { get; set; }
        public Nullable<long> RankFirst { get; set; }
        public int IsLast { get; set; }
        public int IsFirst { get; set; }
        public Nullable<bool> IsNotificationEnabled { get; set; }
    }
}
