//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlighPlanAssignedRegister
    {
        public int FlightPlanItemId { get; set; }
        public int FlightPlanId { get; set; }
        public int PlannedRegisterId { get; set; }
        public int RegisterId { get; set; }
        public string Register { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string DateFromTo { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string FlightType { get; set; }
        public Nullable<int> AirlineOperatorsID { get; set; }
        public string FlightNumber { get; set; }
        public int FromAirport { get; set; }
        public int ToAirport { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public int FlightH { get; set; }
        public int FlightM { get; set; }
        public string FlightPlan { get; set; }
        public int CustomerId { get; set; }
        public string Customer { get; set; }
        public string FromAirportName { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<int> FromAirportCityId { get; set; }
        public string ToAirportName { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> ToAirportCityId { get; set; }
        public string FromAirportCity { get; set; }
        public string ToAirportCity { get; set; }
        public string AircraftType { get; set; }
        public string FromCity { get; set; }
        public string FromContry { get; set; }
        public string FromSortName { get; set; }
        public string ToCity { get; set; }
        public string ToSortName { get; set; }
        public string ToCountry { get; set; }
        public Nullable<decimal> ToLatitude { get; set; }
        public Nullable<decimal> ToLongitude { get; set; }
        public Nullable<decimal> FromLatitude { get; set; }
        public Nullable<decimal> FromLongitude { get; set; }
        public Nullable<int> RouteId { get; set; }
    }
}
