//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightFuel
    {
        public int FlightId { get; set; }
        public Nullable<decimal> FuelDeparture { get; set; }
        public Nullable<decimal> FuelArrival { get; set; }
        public Nullable<decimal> FuelBurned { get; set; }
        public Nullable<decimal> AVGFuelBurned { get; set; }
        public Nullable<decimal> AvgVar { get; set; }
        public Nullable<decimal> FPFuel { get; set; }
        public Nullable<decimal> FPVar { get; set; }
        public Nullable<int> TotalPax { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<byte> FlightM { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string RouteIATA { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string AircraftType { get; set; }
        public string Register { get; set; }
        public string FuelUnit { get; set; }
        public Nullable<int> FuelUnitID { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<int> BoxId { get; set; }
        public Nullable<int> CargoWeight { get; set; }
        public string CargoUnit { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public Nullable<int> CargoUnitID { get; set; }
        public Nullable<int> BaggageWeight { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public int PositionId { get; set; }
        public int EmployeeId { get; set; }
        public string Position { get; set; }
        public string PID { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string Name { get; set; }
    }
}
