//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPersonExperiense
    {
        public int PersonId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string Employer { get; set; }
        public Nullable<int> AircraftTypeId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Organization { get; set; }
        public string JobTitle { get; set; }
        public string AircraftType { get; set; }
        public int Id { get; set; }
    }
}
